"""Final capacity analysis with cache layers."""

print("=" * 65)
print("CAPACITY ANALYSIS WITH CACHE LAYERS")
print("=" * 65)
print()
print("--- CACHE ARCHITECTURE ---")
print()
print("Layer 1: Answer Cache (Redis)")
print("  TTL: 30 minutes")
print("  Key: version + prompt_hash + model + query")
print("  Condition: single-turn only (history empty)")
print("  Hit: return immediately, 0 DB, 0 LLM")
print()
print("Layer 2: Tool Data Cache (Redis)")
print("  Price:   TTL = 15 min (gia thay doi)")
print("  Specs:   TTL = 4 hours (version-aware)")
print("  Colors:  TTL = 4 hours")
print("  Models:  TTL = 4 hours")
print("  Hit: skip DB query, return from Redis (~1ms)")
print()
print("Layer 3: Hybrid Search Cache (Redis)")
print("  TTL: 2 hours")
print("  Key: version + query + model + top_k")
print("  Hit: skip Qdrant + Embedding API (~3ms saved)")
print()
print("Layer 4: Embedding Cache (Redis)")
print("  TTL: 7 days")
print("  Key: model + sha1(text)")
print("  Hit: skip OpenRouter embed API (~2-3s saved)")
print()
print("Layer 5: In-Memory Cache")
print("  System prompt: 5 min")
print("  Tool schemas: 5 min")
print("  Data version: 60s")
print()

print("=" * 65)
print("REQUEST FLOW WITH CACHE")
print("=" * 65)
print()
print("User Request")
print("  |")
print("  v")
print("Answer Cache (Redis) --> HIT? --> DONE (1ms, no DB, no LLM)")
print("  |")
print("  v (MISS)")
print("Agent Run")
print("  |")
print("  +-> Tool Calls --> Tool Cache --> HIT? --> skip DB")
print("  |                            |")
print("  |                            v (MISS)")
print("  |                        DB Query (~3ms)")
print("  |")
print("  +-> LLM Call (DeepInfra)")
print("  |")
print("  +-> Search (if needed) --> Search Cache --> HIT? --> skip Qdrant")
print("  |")
print("  v")
print("Cache Answer (Redis, 30 min)")
print()

print("=" * 65)
print("SCENARIO: 500 CONCURRENT USERS")
print("=" * 65)
print()

scenarios = [
    ("Optimistic (similar queries)", 0.75, 0.85),
    ("Realistic (mixed queries)", 0.50, 0.70),
    ("Pessimistic (diverse queries)", 0.25, 0.50),
]

for name, answer_hit_rate, tool_hit_rate in scenarios:
    print("--- {} ---".format(name))
    print("  Answer cache hit rate: {:.0f}%".format(answer_hit_rate * 100))
    print("  Tool data cache hit rate: {:.0f}%".format(tool_hit_rate * 100))
    print()

    cache_hits = int(500 * answer_hit_rate)
    cache_misses = 500 - cache_hits

    print("  Cache HITS: {} requests".format(cache_hits))
    print("    - Redis GET only: ~1ms each")
    print("    - DB pool needed: 0")
    print("    - LLM calls needed: 0")
    print("    - Total time: ~{:.1f}s (parallel)".format(cache_hits * 1 / 1000))
    print()

    tool_queries = int(cache_misses * (1 - tool_hit_rate))
    print("  Cache MISSES: {} requests".format(cache_misses))
    print("    - Tool data from cache: {}".format(cache_misses - tool_queries))
    print("    - Tool data from DB: {}".format(tool_queries))
    print("    - DB queries needed: ~{} (+ {} for session)".format(tool_queries, cache_misses))
    print("    - LLM calls needed: {}".format(cache_misses))
    print()

    total_db = tool_queries + cache_misses
    batches = (total_db + 29) // 30
    queue_time = batches * 3

    print("  DB POOL USAGE:")
    print("    - Total queries: {}".format(total_db))
    print("    - With 30 connections: {} batches".format(batches))
    print("    - Queue wait: ~{}ms".format(queue_time))
    print("    - Pool utilization: {:.1f}%".format(total_db / 30))
    print()

    print("  REAL BOTTLENECK: LLM API")
    print("    - {} LLM calls needed".format(cache_misses))
    print("    - DeepInfra free tier: ~10-20 RPM")
    print("    - DeepInfra paid tier: ~100-1000 RPM")
    print(
        "    - Time to process: {:.0f}s (free) or {:.1f}s (paid)".format(
            cache_misses / 15 * 60, cache_misses / 500 * 60
        )
    )
    print()

print("=" * 65)
print("MAX CAPACITY BY BOTTLENECK")
print("=" * 65)
print()
print("| Bottleneck          | Free Tier      | Paid Tier       |")
print("|---------------------|----------------|-----------------|")
print("| DB Pool (30 conn)   | ~10,000 QPS    | ~10,000 QPS     |")
print("| Neon Pooler         | ~200 concurrent| ~500+ concurrent|")
print("| Redis (Upstash)     | ~10,000 RPM    | ~10,000 RPM     |")
print("| LLM (DeepInfra)     | ~10-20 RPM     | ~100-1000 RPM   |")
print("| Rate Limiter        | 30 RPM/IP      | 30 RPM/IP       |")
print("| Backpressure        | 50 concurrent  | 50 concurrent   |")
print()

print("=" * 65)
print("FINAL VERDICT")
print("=" * 65)
print()
print("With cache layers:")
print()
print("  500 concurrent users, all sending at once:")
print("  - If 70% cache hit: 350 users get response in ~1ms")
print("  - Remaining 150 users need LLM (real bottleneck)")
print("  - DB pool handles 150 users easily (~15ms queue)")
print("  - LLM takes ~5-15s per request")
print()
print("  MAX CONCURRENT (system can handle):")
print("  - With cache: 200-300 concurrent users")
print("    (most are cache hits, very few need LLM)")
print("  - Without cache: 50-80 concurrent users")
print("    (every user needs LLM)")
print()
print("  500 concurrent users:")
print("  - CACHE HITS: Yes, system handles it")
print("  - CACHE MISSES: Need DeepInfra paid tier")
print("  - DB pool: NOT the bottleneck anymore")
print()
print("  RECOMMENDATION:")
print("  - Free tier: 50-100 concurrent (realistic)")
print("  - Paid DeepInfra: 200-300 concurrent")
print("  - For 500: need paid everything + queue system")
